### ISSUE TITLE
Could the code for generating the shape motion dataset also be released?

### ISSUE THREAD

**Issue by Dawn90** [sergeytulyakov/mocogan#10]
Hello,
This is such a nice job. The codes are clean and easy to follow. 
Recently, I'm working on video disentangling. Could I have the code for generating the shape motion dataset? Thanks a lot!
Dong

**Comment by sergeytulyakov** [comment]
Hello,

At this point there are no plans to release this code. But it's quite easy. 
1. Randomly sample content (shape, color, size, initial position)
2. Randomly sample several anchor points for the Bezier curve
3. Compute Bezier curve
4. Draw the shape along the curve
