### ISSUE TITLE
Got segmentation fault(core dumped) when tried to run train.py

### ISSUE THREAD

**Issue by vipulbjj** [sergeytulyakov/mocogan#11]
I've not used docker and installed dependencies by pip as instructed in the wiki.
Actually, the error is coming in loggers file while importing tensorflow.
I found out this while debugging this error. Please provide a solution @sergeytulyakov
Segmentation fault (core dumped)
train.py calls trainers.py which calls loggers.py.
#6

**Comment by sergeytulyakov** [comment]
Are you able to import tensorflow in any other project?

**Comment by vipulbjj** [comment]
Yes
I simply checked it by importing in python.
It works.

**Comment by vipulbjj** [comment]
[https://github.com/tensorflow/tensorflow/issues/2034](url)
Is it something related to this link?

**Comment by Jehereg** [comment]
Not sure if it's the same situation (or even still relevant). 
In my setup the Segmentation fault occurs when I import torch before tensorflow.
In train.py : Importing Trainer before torch helped.

**Comment by vipulbjj** [comment]
@Jehereg  That worked for me. Thanks. But I still wonder why is this happening?
Importing torch before tensorflow giving segmentation fault is sort of a weird problem.
