### ISSUE TITLE
Action-conditional video generator inconsistent with the paper claim?

### ISSUE THREAD

**Issue by sunxm2357** [sergeytulyakov/mocogan#13]
Hello, 

I am reading through the paper and the code. In paper, Section 3.1 claimed that if the video generation is conditioned on action category, the input to GRU should be a concatenation of one-hot action vector and a random vector. However in `src/models.py` Line 261, https://github.com/sergeytulyakov/mocogan/blob/d59b5b7bf021b0473f20f62659f5c8685fa6cf21/src/models.py#L261
it seems that you just combine the one-hot action vector with the output of GRU instead of feeding action vector as an input to GRU.

I am very confused with this inconsistency. If my understanding is not right, feel free to correct me.

**Comment by sergeytulyakov** [comment]
Hello,

Thanks for pointing this out. In the paper we tested different schemes for conditioning, one of which was to add the z_category to the generator (the current code). It is trivial to change the code such that the conditioning is fed into the recurrent module. 

Sorry for confusion
