### ISSUE TITLE
results on UCF101

### ISSUE THREAD

**Issue by wyhsirius** [sergeytulyakov/mocogan#14]
Hi, thanks for this great work. Is it possible for you to provide the generated videos on UCF101 ?

**Comment by dmckee5** [comment]
My thanks as well for this work and the released code! As a followup, will the trained models for UCF101 be released at any point? Would be very helpful to have available.

**Comment by Cpruce** [comment]
I trained on UCF101, but my generated results aren't great. I too would be interested in a UCF101 pretrained model

**Comment by sergeytulyakov** [comment]
The results on UCF101 don't look great in the paper as well. In fact, UCF101 is still very challenging for generation. We're not planning on releasing the pretrained models
