### ISSUE TITLE
Unwanted repeatition of the action in the Generated videos

### ISSUE THREAD

**Issue by ahmadpgh** [sergeytulyakov/mocogan#19]
First off, thanks for the awesome paper and also for the well-maintained code!

How can I avoid repetition in the result/generated videos and make sure they are not going to be squeezed (and repeated) during the whole time span that I have in the original videos. FYI, I have the videos of the 256 frames but when I work with different settings of `video_length` I see repetition or other inconsistency unless I set `video_length` equal to 256 which ends up to be very costly
Very thanks in advance

**Comment by sergeytulyakov** [comment]
In this case, the training framework should be changed a little bit. You should use something as truncated back propagation. Repeating videos is something mocogan produces
