### ISSUE TITLE
Code for Image-to-video Translation

### ISSUE THREAD

**Issue by gitzyong812** [sergeytulyakov/mocogan#24]
Dear author,

You have mentioned that the mocogan model can be adapted to the image-to-video task. Would you mind to share your implementation?

Thank you so much

**Comment by Orange066** [comment]
I also want to see this image-to-video network. Would you mind to share your implementation?

**Comment by WangJincheng888** [comment]
I also want to see this image-to-video network. Would you mind to share your implementation?

**Comment by sergeytulyakov** [comment]
Unfortunately this version is not available publicly.
