### ISSUE TITLE
RuntimeError: arguments are located on different GPUs

### ISSUE THREAD

**Issue by Fanny-Yuan** [sergeytulyakov/mocogan#30]
Hi, I was running your code on my GPUs but the error occurred. I tried to set one GPU but the problem still exists. I was wondering if you know how to solve that?

**Comment by Fanny-Yuan** [comment]
Supplement: I was running train.py using dynamic expression dataset.

**Comment by Fanny-Yuan** [comment]
![image](https://user-images.githubusercontent.com/52789487/116084682-9d748680-a6d0-11eb-97fe-88bc9c29cc1b.png)

**Comment by cyhhhhhhit** [comment]
Hi, I've got the same problem. Is there any new progress about this question?

**Comment by sergeytulyakov** [comment]
Hi, the framework was not implemented to support multigpu training. It has to be changed to allow for this. I'm happy to review a PR if anyone fixed this.
