### ISSUE TITLE
Dataset Formatter

### ISSUE THREAD

**Issue by jhawgs** [sergeytulyakov/mocogan#32]
Is there any code that converts an mp4 (or other video format) to the 2-dimensional jpgs that are input for training that could be included or referenced?

**Comment by vladyushchenko** [comment]
Hey @jhawgs, you can extract separate frames from mp4 videos using ffmpeg and then you may also find [this script](https://github.com/VladYushchenko/MDPVideoGeneration/blob/master/mdp_video/transform/raw2mocogan.py) helpful to transform separate videos to MoCoGAN input format. 

However, you may need to adapt code/structure your sequences in a way that is assumed by the script.
Good luck!

**Comment by jhawgs** [comment]
Sounds good! Thank you!
