### ISSUE TITLE
got segmentation fault when tried to run train .py

### ISSUE THREAD

**Issue by maniyar2jaimin** [sergeytulyakov/mocogan#6]
I follow the steps from wiki and build the environment manually. I am not using docker. I got segmentation fault (core dump) error while running 
this command
python train.py  \
    --image_batch 32 \
    --video_batch 32 \
    --use_infogan \
    --use_noise \
    --noise_sigma 0.1 \
    --image_discriminator PatchImageDiscriminator \
    --video_discriminator CategoricalVideoDiscriminator \
    --print_every 100 \
    --every_nth 2 \
    --dim_z_content 50 \
    --dim_z_motion 10 \
    --dim_z_category 4 \
    ../data/actions ../logs/actions

Can you please help me regard this

**Comment by sergeytulyakov** [comment]
Which version of python are you using? Segmentation fault is a very generic error, could provide any details? Like which line causes the error

**Comment by maniyar2jaimin** [comment]
I am using python 2.7
tensorflow version 1.4
tensorflow-gpu version 1.4
tensorboard 0.4.x
numpy 1.13.x

Segmentation Fault (core dump)
occurs while executing
from trainers import Trainer

**Comment by sergeytulyakov** [comment]
Still not clear.
What about pytorch? Which line in trainer.py causes the error?

**Comment by maniyar2jaimin** [comment]
version of pytorch 0.20-post3 prebuilt binries compiled with cuda8
when I compile trainers.py separately I did not get any error

but when it is imported in train.py at line no. 56 
from trainers import Trainer this segmentation fault is happening

hope this helps

**Comment by sergeytulyakov** [comment]
@maniyar2jaimin Segmentation fault could mean anything. I suggest you try one of the following things:
1. Use the provided docker image and see if it works for you
2. Find the line at which the error actually happens and try to resolve the issue. For this check what happens when you import from trainers. Which line there causes the error. I would assume it cannot import some of the dependencies.

**Comment by vipulbjj** [comment]
Actually, the error is coming in loggers file while importing tensorflow.
I found out this while debugging this error. Please provide a solution @sergeytulyakov 
Segmentation fault (core dumped)
