### ISSUE TITLE
Discriminators structures are not same as in paper?

### ISSUE THREAD

**Issue by chmxu** [sergeytulyakov/mocogan#9]
Hi, I've read the MocoGAN paper and in the supplementary materials and it said that stride and padding of 3D Conv in Dis_v are  "equal for all the dimensions in each layer", which is obviously different from your code. So which one is the actual one you used in your paper?

**Comment by sergeytulyakov** [comment]
Hi,

I assume you mean video discriminators, thanks for pointing this out. I'll update the supplement. The code is this repository was used to generate all the results in the paper.
